services:
  - type: web
    name: stress-detection-web
    env: python
    plan: free
    rootDir: web_app
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg git-lfs
      git lfs install
      git lfs pull
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
